name: Download TF Vars

on:
  workflow_run:
    workflows: ["Upload TF Vars"]
    types:
      - completed

jobs:
  download:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download artifact from previous workflow
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          run_id: ${{ github.event.workflow_run.id }}
          name: tfvars-artifact

      - name: Verify
        run: |
          ls -la
          cat terraform.tfvars
