name: Upload TF Vars

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create tfvars
        run: |
          echo 'project_id = "demo"' > terraform.tfvars

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfvars-artifact
          path: terraform.tfvars
